package ai

import "time"

// UserRequest represents a parsed user request
type UserRequest struct {
	RawRequest string     // Original user input
	Intent     string     // "create_test", "create_page_object", "create_method", etc.
	Entities   []Entity   // Extracted entities
	TaskType   string     // "functional_test", "api_test", "page_object", etc.
	Framework  string     // From project config
	Embedding  []float64  // Vector representation for similarity search
}

// Entity represents an extracted entity from the request
type Entity struct {
	Type   string // "page", "element", "method", "test", "field"
	Name   string // "LoginPage", "usernameField", etc.
	Action string // "click", "verify", "navigate", "enter", etc.
}

// SearchResult represents a retrieved code chunk
type SearchResult struct {
	ChunkID       int                    // ID from chunks table
	ChunkType     string                 // "class", "method", "field"
	EntityID      int                    // ID from classes/methods/fields table
	Content       string                 // Enriched code content
	BM25Score     float64                // Keyword-based score
	SemanticScore float64                // Embedding-based score
	FinalScore    float64                // Hybrid score
	Metadata      map[string]interface{} // Additional info
}

// Example represents a few-shot learning example
type Example struct {
	ID          int     // ID from pattern_examples table
	Type        string  // "positive", "negative"
	Description string  // Pattern description
	Code        string  // Example code
	Explanation string  // Why this is good/bad
	Similarity  float64 // Similarity to user request
}

// AssembledPrompt represents the complete prompt ready for LLM
type AssembledPrompt struct {
	SystemPrompt     string   // Static instructions (cached)
	UserPrompt       string   // Dynamic content
	CacheBreakpoints []string // Markers for Claude's prompt caching
	TotalTokens      int      // Estimated total tokens
	CachedTokens     int      // Estimated cached tokens
	DynamicTokens    int      // Estimated dynamic tokens
}

// GeneratedCode represents code generated by LLM
type GeneratedCode struct {
	Code          string    // The generated code
	Language      string    // "java"
	CodeType      string    // "test", "page_object", "step_definition", "utility"
	ClassName     string    // If applicable
	PackageName   string    // Package name (e.g., "com.example.pages")
	SuggestedPath string    // Suggested file path (e.g., "com/example/pages/LoginPage.java")
	MethodName    string    // If applicable
	Imports       []string  // Required imports
	GeneratedAt   time.Time // When it was generated
}

// ConversationMessage represents a single message in a conversation
type ConversationMessage struct {
	Role      string         // "user" or "assistant"
	Content   string         // Message content
	Code      *GeneratedCode // If assistant generated code
	Timestamp time.Time      // When message was sent
}

// ConversationHistory tracks multi-turn conversations
type ConversationHistory struct {
	SessionID string                // Unique session identifier
	Messages  []ConversationMessage // All messages in this session
	MaxTurns  int                   // Keep only last N turns (default: 5)
}

// ContextBuilderMetrics tracks performance metrics
type ContextBuilderMetrics struct {
	RetrievalLatency      time.Duration // Time spent retrieving context
	BM25ResultCount       int           // Number of BM25 results
	SemanticResultCount   int           // Number of semantic results
	HybridResultCount     int           // Number of final results
	AverageRelevanceScore float64       // Average score of results
	ExampleSelectionTime  time.Duration // Time spent selecting examples
	TotalTokens           int           // Total tokens in prompt
	CachedTokens          int           // Tokens that will be cached
	DynamicTokens         int           // Tokens that won't be cached
	EstimatedCost         float64       // Estimated API cost ($)
}

// CodeGenerationResult represents the complete result of code generation
type CodeGenerationResult struct {
	ContextMetrics   *ContextBuilderMetrics // Metrics from context building
	LLMResponse      *GenerateResponse      // Response from LLM
	ParsedResponse   *ParsedResponse        // Parsed code and sections
	ValidationErrors []ValidationError      // Code validation results
	TotalTime        time.Duration          // Total generation time
}

// Config holds configuration for Context Builder
type Config struct {
	// Hybrid Retrieval
	SemanticWeight float64 // Alpha for fusion (default: 0.65)
	TopK           int     // Number of chunks to retrieve (default: 5)

	// BM25 Parameters
	BM25_K1 float64 // Term frequency saturation (default: 1.2)
	BM25_B  float64 // Length normalization (default: 0.75)

	// Few-Shot Selection
	PositiveExamples int // Number of positive examples (default: 3)
	NegativeExamples int // Number of negative examples (default: 1)

	// Chunking
	MaxChunkTokens int // Max tokens per chunk (default: 500)
	ChunkOverlap   int // Overlap between chunks (default: 50)

	// Embeddings
	EmbeddingServiceURL string // URL of embedding service (default: "http://localhost:5000")
	EmbeddingDimension  int    // Dimension (default: 384)

	// Prompt Caching
	EnableCaching bool // Use prompt caching (default: true)

	// Conversation
	MaxConversationTurns int // Keep last N turns (default: 5)

	// LLM Configuration
	LLMConfig LLMConfig // LLM client configuration
}

// DefaultConfig returns default configuration
func DefaultConfig() Config {
	return Config{
		SemanticWeight:       0.65,
		TopK:                 5,
		BM25_K1:              1.2,
		BM25_B:               0.75,
		PositiveExamples:     3,
		NegativeExamples:     1,
		MaxChunkTokens:       500,
		ChunkOverlap:         50,
		EmbeddingServiceURL:  "http://localhost:5000",
		EmbeddingDimension:   384,
		EnableCaching:        true,
		MaxConversationTurns: 5,
		LLMConfig:            DefaultLLMConfig(),
	}
}
